package com.varunasoft.farmer.domain;
// Generated 2 Jan, 2018 10:00:37 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AddressFarmer generated by hbm2java
 */
@Entity
@Table(name = "ADDRESS_FARMER", catalog = "DayBase")
public class AddressFarmer implements java.io.Serializable {

	private String addressId;
	private FarmersDetails farmersDetails;
	private PincodeDetails pincodeDetails;
	private String addressLine1;
	private String addressLine2;
	private String addressType;

	public AddressFarmer() {
	}

	public AddressFarmer(String addressId) {
		this.addressId = addressId;
	}

	public AddressFarmer(String addressId, FarmersDetails farmersDetails, PincodeDetails pincodeDetails,
			String addressLine1, String addressLine2, String addressType) {
		this.addressId = addressId;
		this.farmersDetails = farmersDetails;
		this.pincodeDetails = pincodeDetails;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.addressType = addressType;
	}

	@Id

	@Column(name = "ADDRESS_ID", unique = true, nullable = false, length = 45)
	public String getAddressId() {
		return this.addressId;
	}

	public void setAddressId(String addressId) {
		this.addressId = addressId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Farmer_ID")
	public FarmersDetails getFarmersDetails() {
		return this.farmersDetails;
	}

	public void setFarmersDetails(FarmersDetails farmersDetails) {
		this.farmersDetails = farmersDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PINCODE_DETAILS")
	public PincodeDetails getPincodeDetails() {
		return this.pincodeDetails;
	}

	public void setPincodeDetails(PincodeDetails pincodeDetails) {
		this.pincodeDetails = pincodeDetails;
	}

	@Column(name = "AddressLine_1", length = 300)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "AddressLine_2", length = 300)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "Address_Type", length = 45)
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

}
