package com.varunasoft.farmer.domain;
// Generated 3 Jan, 2018 1:28:46 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EducationDetails generated by hbm2java
 */
@Entity
@Table(name = "EDUCATION_DETAILS", catalog = "DayBase")
public class EducationDetails implements java.io.Serializable {

	private String farmerEducationId;
	private String boardUniversity;
	private String farmerEducationLevel;
	private Set<FarmersDetails> farmersDetailses = new HashSet<FarmersDetails>(0);

	public EducationDetails() {
	}

	public EducationDetails(String farmerEducationId, String farmerEducationLevel) {
		this.farmerEducationId = farmerEducationId;
		this.farmerEducationLevel = farmerEducationLevel;
	}

	public EducationDetails(String farmerEducationId, String boardUniversity, String farmerEducationLevel,
			Set<FarmersDetails> farmersDetailses) {
		this.farmerEducationId = farmerEducationId;
		this.boardUniversity = boardUniversity;
		this.farmerEducationLevel = farmerEducationLevel;
		this.farmersDetailses = farmersDetailses;
	}

	@Id

	@Column(name = "Farmer_Education_ID", unique = true, nullable = false, length = 45)
	public String getFarmerEducationId() {
		return this.farmerEducationId;
	}

	public void setFarmerEducationId(String farmerEducationId) {
		this.farmerEducationId = farmerEducationId;
	}

	@Column(name = "Board_University", length = 45)
	public String getBoardUniversity() {
		return this.boardUniversity;
	}

	public void setBoardUniversity(String boardUniversity) {
		this.boardUniversity = boardUniversity;
	}

	@Column(name = "Farmer_Education_Level", nullable = false, length = 45)
	public String getFarmerEducationLevel() {
		return this.farmerEducationLevel;
	}

	public void setFarmerEducationLevel(String farmerEducationLevel) {
		this.farmerEducationLevel = farmerEducationLevel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "educationDetails")
	public Set<FarmersDetails> getFarmersDetailses() {
		return this.farmersDetailses;
	}

	public void setFarmersDetailses(Set<FarmersDetails> farmersDetailses) {
		this.farmersDetailses = farmersDetailses;
	}

}
