package com.varunasoft.farmer.domain;
// Generated 2 Jan, 2018 10:00:37 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PincodeDetails generated by hbm2java
 */
@Entity
@Table(name = "PINCODE_DETAILS", catalog = "DayBase")
public class PincodeDetails implements java.io.Serializable {

	private String pincodeDetailsId;
	private String pincode;
	private String postOfficeName;
	private String taluk;
	private String circle;
	private String district;
	private String division;
	private String region;
	private String state;
	private String country;
	private Set<AddressFarmer> addressFarmers = new HashSet<AddressFarmer>(0);

	public PincodeDetails() {
	}

	public PincodeDetails(String pincodeDetailsId) {
		this.pincodeDetailsId = pincodeDetailsId;
	}

	public PincodeDetails(String pincodeDetailsId, String pincode, String postOfficeName, String taluk, String circle,
			String district, String division, String region, String state, String country,
			Set<AddressFarmer> addressFarmers) {
		this.pincodeDetailsId = pincodeDetailsId;
		this.pincode = pincode;
		this.postOfficeName = postOfficeName;
		this.taluk = taluk;
		this.circle = circle;
		this.district = district;
		this.division = division;
		this.region = region;
		this.state = state;
		this.country = country;
		this.addressFarmers = addressFarmers;
	}

	@Id

	@Column(name = "PINCODE_Details_ID", unique = true, nullable = false, length = 45)
	public String getPincodeDetailsId() {
		return this.pincodeDetailsId;
	}

	public void setPincodeDetailsId(String pincodeDetailsId) {
		this.pincodeDetailsId = pincodeDetailsId;
	}

	@Column(name = "PINCODE", length = 300)
	public String getPincode() {
		return this.pincode;
	}

	public void setPincode(String pincode) {
		this.pincode = pincode;
	}

	@Column(name = "PostOffice_Name", length = 300)
	public String getPostOfficeName() {
		return this.postOfficeName;
	}

	public void setPostOfficeName(String postOfficeName) {
		this.postOfficeName = postOfficeName;
	}

	@Column(name = "Taluk", length = 100)
	public String getTaluk() {
		return this.taluk;
	}

	public void setTaluk(String taluk) {
		this.taluk = taluk;
	}

	@Column(name = "Circle", length = 100)
	public String getCircle() {
		return this.circle;
	}

	public void setCircle(String circle) {
		this.circle = circle;
	}

	@Column(name = "District", length = 100)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "Division", length = 100)
	public String getDivision() {
		return this.division;
	}

	public void setDivision(String division) {
		this.division = division;
	}

	@Column(name = "Region", length = 100)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "State", length = 100)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "Country", length = 100)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pincodeDetails")
	public Set<AddressFarmer> getAddressFarmers() {
		return this.addressFarmers;
	}

	public void setAddressFarmers(Set<AddressFarmer> addressFarmers) {
		this.addressFarmers = addressFarmers;
	}

}
