package com.varunasoft.farmer.domain;
// Generated 3 Jan, 2018 1:28:46 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * FarmersDetails generated by hbm2java
 */
@Entity
@Table(name = "FARMERS_DETAILS", catalog = "DayBase")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class FarmersDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String farmerId;
	private EducationDetails educationDetails;
	private String firstName;
	private String lastName;
	private String middleName;
	private String fatherName;
	private String motherName;
	private Date dob;
	private Integer mobileNumber;
	private Integer phoneNumber;
	private String maritalStatus;
	private String emailId;
	private String bloodGroup;
	private Long annualIncome;
	private String pancardNo;
	private String voterId;
	private String aadharId;
	private String referenceId;
	private String drivingLicenceId;
	private Date creationDate;
	private Date updationDate;
	private Date lastLoginDate;

	public FarmersDetails() {
	}

	public FarmersDetails(String farmerId) {
		this.farmerId = farmerId;
	}

	public FarmersDetails(String farmerId, EducationDetails educationDetails, String firstName, String lastName,
			String middleName, String fatherName, String motherName, Date dob, Integer mobileNumber,
			Integer phoneNumber, String maritalStatus, String emailId, String bloodGroup, Long annualIncome,
			String pancardNo, String voterId, String aadharId, String referenceId, String drivingLicenceId,
			Date creationDate, Date updationDate, Date lastLoginDate) {
		this.farmerId = farmerId;
		this.educationDetails = educationDetails;
		this.firstName = firstName;
		this.lastName = lastName;
		this.middleName = middleName;
		this.fatherName = fatherName;
		this.motherName = motherName;
		this.dob = dob;
		this.mobileNumber = mobileNumber;
		this.phoneNumber = phoneNumber;
		this.maritalStatus = maritalStatus;
		this.emailId = emailId;
		this.bloodGroup = bloodGroup;
		this.annualIncome = annualIncome;
		this.pancardNo = pancardNo;
		this.voterId = voterId;
		this.aadharId = aadharId;
		this.referenceId = referenceId;
		this.drivingLicenceId = drivingLicenceId;
		this.creationDate = creationDate;
		this.updationDate = updationDate;
		this.lastLoginDate = lastLoginDate;
	}

	@Id

	@Column(name = "FARMER_ID", unique = true, nullable = false, length = 45)
	public String getFarmerId() {
		return this.farmerId;
	}

	public void setFarmerId(String farmerId) {
		this.farmerId = farmerId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "EDUCATION")
	/*@JsonManagedReference*/
	public EducationDetails getEducationDetails() {
		return this.educationDetails;
	}

	public void setEducationDetails(EducationDetails educationDetails) {
		this.educationDetails = educationDetails;
	}

	@Column(name = "FIRST_NAME", length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "LAST_NAME", length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "MIDDLE_NAME", length = 45)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "FATHER_NAME", length = 45)
	public String getFatherName() {
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	@Column(name = "MOTHER_NAME", length = 45)
	public String getMotherName() {
		return this.motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "MOBILE_NUMBER")
	public Integer getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(Integer mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Column(name = "PHONE_NUMBER")
	public Integer getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(Integer phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "MARITAL_STATUS", length = 45)
	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	@Column(name = "EMAIL_ID", length = 100)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "BLOOD_GROUP", length = 20)
	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	@Column(name = "ANNUAL_INCOME", precision = 10, scale = 0)
	public Long getAnnualIncome() {
		return this.annualIncome;
	}

	public void setAnnualIncome(Long annualIncome) {
		this.annualIncome = annualIncome;
	}

	@Column(name = "PANCARD_NO", length = 45)
	public String getPancardNo() {
		return this.pancardNo;
	}

	public void setPancardNo(String pancardNo) {
		this.pancardNo = pancardNo;
	}

	@Column(name = "VOTER_ID", length = 45)
	public String getVoterId() {
		return this.voterId;
	}

	public void setVoterId(String voterId) {
		this.voterId = voterId;
	}

	@Column(name = "AADHAR_ID", length = 45)
	public String getAadharId() {
		return this.aadharId;
	}

	public void setAadharId(String aadharId) {
		this.aadharId = aadharId;
	}

	@Column(name = "REFERENCE_ID", length = 45)
	public String getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}

	@Column(name = "DRIVING_LICENCE_ID", length = 45)
	public String getDrivingLicenceId() {
		return this.drivingLicenceId;
	}

	public void setDrivingLicenceId(String drivingLicenceId) {
		this.drivingLicenceId = drivingLicenceId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATION_DATE", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATION_DATE", length = 19)
	public Date getUpdationDate() {
		return this.updationDate;
	}

	public void setUpdationDate(Date updationDate) {
		this.updationDate = updationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_LOGIN_DATE", length = 19)
	public Date getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

}
